name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macOS-latest # enables hardware acceleration in the virtual machine
    timeout-minutes: 55
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and Unit tests with Gradle
      run: ./gradlew build --info

    - name: Accept Android SDKs Licences
      run: yes | /Users/runner/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Upload build outputs (APKs)
      uses: actions/upload-artifact@v3
      with:
       name: build-outputs
       path: app/build/outputs
    - name: Upload build reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
       name: build-reports
       path: app/build/reports

    - name: Run Instrumented tests
      run: ./gradlew pixel3api30DebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect --info

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: '*/build/reports/androidTests'