name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and Unit tests with Gradle
      run: ./gradlew build --info
    - name: Accept the Android SDK package Licence
      run: |
        ls -Alth
        ls -ARl /usr/local/lib/android/sdk/
        /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
    - name: Run UI test
      run: ./gradlew pixel3api30DebugAndroidTest -Pandroid.testoptions.manageddevices.emulator.gpu=swiftshader_indirect --info
